services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: Splendor01
    volumes:
      - ./database_volume:/var/lib/postgresql/data_db